"""Removed Note field

Revision ID: 0c77a3f9d736
Revises: e1b48089fa6a
Create Date: 2025-06-01 08:18:13.320556

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "0c77a3f9d736"
down_revision: Union[str, None] = "e1b48089fa6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activitecandidature", "note")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activitecandidature", sa.Column("note", sa.VARCHAR(length=12), nullable=False)
    )
    # ### end Alembic commands ###
